web:
  image: danelbert/spellsheet:production
  ports:
    - "4000:80"
  environment:
    - PASSENGER_APP_ENV=production
  env_file: /etc/default/spellsheet
  volumes:
    - /var/log/spellsheet/:/home/app/spellsheet/log