version: '3'

services:
  mysql:
    image: mysql:5.6
    environment:
      - MYSQL_ROOT_PASSWORD=mysupersecret
      - MYSQL_DATABASE=spellsheet
      - MYSQL_USER=spellsheet
      - MYSQL_PASSWORD=password
    volumes:
      - sql-data:/var/lib/mysql

  web:
    build: .
    image: 'danelbert/spellsheet'
    ports:
      - "3000:80"
    links:
      - mysql

volumes:
  sql-data:
    driver: local