# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f27dbae802b5143442d48ff10a90d3b931fe87a9c135be71fa4978e509fedb8e71c315421efafcb05ce641f27eed1f93b5eb3da7ea03341d89b15bd9ab206166

test:
  secret_key_base: 1e79e3a60936fcce7d88100e313a607ce408086c3a28669d3c47cb6c5ea0946bdc9b7b6a19fda1c2c7ec9b43379e8dd734f0035d8c060867f90dc15bbe8d6e29

docker:
  secret_key_base: 98cee164fc9bff2992faa0fe61178e2dc94a49a7a18bb842ba1dd9e80326f29e2a319be3c6f850b05214b497f63464af493931cdc691e1a8a1a964bd2cf2a682

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
